Enhance exception messages
hrrrrustic/Issueneter pull request #43
Opened 2023-07-14 17:39 UTC by FrediKats

В некоторых местах добавил более подробный текст ошибок.

2023-07-14 18:40 UTC, Bibletoon requested changes

2023-07-14 18:40 UTC, Bibletoon commented on Issueneter.Github/Utility/IssueExtensions.cs
> +            _ => throw new ArgumentOutOfRangeException(nameof(issue), $"Can't determine issue state. State value: {issue.State.Value}")
А почему тут на `IssueneterArgumentException.For` не заменить, кмк почти одинаковые юзкейсы.

2023-07-14 18:40 UTC, Bibletoon commented on Issueneter.Json/IssueneterJsonSerializer.cs
> +            throw new IssueneterValidationException($"Cannot filter for {data}");
1. В сообщении как будто не хватает глагола "Can't *construct/create* filter for {data}"
2. Мне как-то сообщение не очень нравится, тут вроде бы не мы не смогли что-то сделать, а просто пользователь отправил не валидный фильтр

2023-07-14 18:40 UTC, Bibletoon commented on Issueneter.Json/JsonFilterConverter.cs
> +                throw new ArgumentException($"Invalid filter type: {type}");
Если следовать логике предыдущих эксепшенов, то тут наверное тоже OutOfRange должен быть 🤔

2023-07-14 18:44 UTC, Bibletoon commented
Ещё вернул ветку `dev`,  лучше на неё перейти т.к. на мастере будет CI для деплоя (сейчас есть, но не рабочий)

2023-07-15 08:17 UTC, FrediKats commented on Issueneter.Github/Utility/IssueExtensions.cs
> +            _ => throw new ArgumentOutOfRangeException(nameof(issue), $"Can't determine issue state. State value: {issue.State.Value}")
Я использовал `IssueneterArgumentException.For` в тех местах, где происходит switch по типу. В данном же месте он происходит по значению и информация о том, что у issue тип issue не поможет и нужно добавлять информация о тех полях, которые задействованы в switch.

2023-07-15 08:19 UTC, FrediKats commented on Issueneter.Json/JsonFilterConverter.cs
> +                throw new ArgumentException($"Invalid filter type: {type}");
Fixed.

2023-07-15 08:20 UTC, FrediKats commented on Issueneter.Json/IssueneterJsonSerializer.cs
> +            throw new IssueneterValidationException($"Cannot filter for {data}");
Изменил текст на "Filter input data is not valid".

2023-07-15 09:21 UTC, Bibletoon approved these changes

2023-07-16 13:30 UTC, merged