Add message configuration
hrrrrustic/Issueneter pull request #48
Opened 2023-07-15 09:22 UTC by FrediKats

Close #30

Реализовал возможность задать шаблон сообщения в конфигурационном файле, поддержал замену в этом шаблоне подстрок {value.Title} и {value.Url} на информацию из issue / pull request. Добавил тесты, добавил базово документацию.

2023-07-15 11:01 UTC, Bibletoon requested changes
В общем основное несовпадение мыслей у меня именно с универсальностью форматтера, кажется что шанс что нам могут понадобиться кастомные форматтеры для отдельной конкретной сущности как мне кажется крайне мал, так что писать такие бойлерплейтные форматтеры для каждой сущности не очень. Ну и даже если понадобится, поддержать такое лукс лайк не составит проблем (просто подкрутить регистрацию)

2023-07-15 11:01 UTC, Bibletoon commented on Issueneter.Host/appsettings.Development.json
> +    "PullRequestMessageTemplate": "[пр]({entity.Url})"
Думаю это надо будет вынести в конфигурацию для каждого отдельного скана, но может быть в рамках отдельной задачи.

2023-07-15 11:01 UTC, Bibletoon commented on Issueneter.Telegram/Formatters/IssueConfigurableMessageFormatter.cs
> +}
Кажется благодаря генерируемым методам можно написать универсальное решение чтобы поддерживались все доступные поля из сущностей + формат для всех будет гарантированно одинаковый.

2023-07-15 16:08 UTC, hrrrrustic commented
Докину еще, что у меня изначально была идея, что формат сообщения можно будет где-то на UI менять

2023-07-15 17:10 UTC, Bibletoon commented
> Докину еще, что у меня изначально была идея, что формат сообщения можно будет в идеале где-то на UI менять

Ну как раз если конфигурируем формат в рамках скана, то можно его вместе с остальными настройками (репозиторий, орга, чат) менять на UI

2023-07-16 08:25 UTC, FrediKats commented
@Bibletoon, правильно ли я понимаю, что ты предлагаешь в Source Gen добавить логику генерации форматтеров для сущностей?

@hrrrrustic, в данном PR реализовано возможность задавать шаблон. А откуда он будет задаваться - это уже детали, наверное. Достаточно же просто из конфига в базу (или куда UI будет сохранять) перенести и в DI реализацию зарегистрировать, которая будет читать с базы.

2023-07-16 08:45 UTC, Bibletoon commented
> @Bibletoon, правильно ли я понимаю, что ты предлагаешь в Source Gen добавить логику генерации форматтеров для сущностей?

Нет, у нас уже есть сурсген, который позволяет
1. Получить список полей для сущности (`ModelsInfo.AvailableScanSources`)
2. Получить значение поля по его имени (`IFilterable.GetProperty`)

Благодаря этому можно сделать форматтер, который по шаблону {value.FieldName} позволяет работать с любой сущностью и с любым доступным в ней полем

2023-07-16 13:28 UTC, Bibletoon commented on Issueneter.Host/appsettings.Development.json
> +    "PullRequestMessageTemplate": "[пр]({entity.Url})"
Завёл #50

2023-07-16 13:29 UTC, Bibletoon approved these changes

2023-07-19 16:02 UTC, hrrrrustic approved these changes

2023-07-20 18:30 UTC, merged